### ISSUE TITLE
Could you upload it to PyPI?

### ISSUE THREAD

**Issue by yuzheng14** [QuattroMusic/PyMermaid#1]
Downloading to use it is trouble and is unconvenient to multiplex it.

**Comment by QuattroMusic** [comment]
Hi, and thanks for your patience.
As you can see, the project runs slow, but it's already planned to upload it to PyPI whenever we're gonna have a basic functioning graph for each mermaid style (you can check it in the readme.md).
Thanks again for your support on this project.
